---
# The variables file used by all groups. We define the ambari repo and version used across groups.

ambari_version: 2.7.4.0
key_url: http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos7/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
repo_url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/{{ ambari_version }}

# variable used for the database

db: postgres
db_name: ambari
db_username: ambari
db_password: bigdata
db_port: 5432
