---
# The variables file used by all groups. We define set bigtop repo for ambari and hadoop..

repo_url: "http://repos.bigtop.apache.org/releases/1.5.0/centos/7/$basearch"
key_url: "https://dist.apache.org/repos/dist/release/bigtop/KEYS"

