---
## This playbook deploys Ambari server, Ambari clients and postgresql database

# Apply common configuration to all hosts
- hosts: all

  roles:
    - environment
    - ambari-repo
    
  tags:
    - environment
    - ambari-repo


# Configure and deploy ambari server
- hosts: ambari_server

  roles:
    - ambari-server-setup

  tags:
    - ambari-server-setup

# Install the agents on the clients
- hosts: ambari_clients

  roles:
    - ambari-agent

  tags:
    - ambari-agent






