---
## This playbook deploys Ambari server, Ambari clients and postgresql database

# Apply common configuration to all hosts
- hosts: all

  roles:
    - environment

  tags:
    - environment


# Configure and deploy ambari server together with postgres
- hosts: ambari-server

  roles:
    - ambari-server
    - db_install

  tags:
    - ambari-server
    - db_install


- hosts: ambari-server
  become_user: postgres

  roles:
    - db_setup

  tags:
    - db_setup

- hosts: ambari-server

  roles:
    - ambari-server-setup

  tags:
    - ambari-server-setup

- hosts: ambari-clients

  roles:
    - ambari-agent

  tags:
    - ambari-agent






