---
## This playbook deploys Ambari server, Ambari clients and postgresql database

# Apply common configuration to all hosts
- hosts: all

  roles:
    - environment

  tags:
    - environment


# Configure and deploy ambari server together with postgres
- hosts: ambari-server

  roles:
    - ambari-server

  tags:
    - ambari-server

- hosts: ambari-server

  roles:
    - ambari-server-setup

  tags:
    - ambari-server-setup

- hosts: ambari-clients

  roles:
    - ambari-agent

  tags:
    - ambari-agent






