# Ansible role to deploy an Ambari client

---

- name: Install the ambari-agent package
  package:
    name: ambari-agent
    state: latest

- name: Point agent to server
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "hostname=localhost"
    line: "hostname={{ambari_server_hn}}"

- name: Restart ambari-agent
  systemd:
    name: ambari-agent
    state: restarted
    
