---
# This role will prepare the environment 


- name: Add or modify nofile soft limit 
  pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: "64000"

# Set /etc/hosts 

- name: insert hostname in hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ item }}'
    insertafter: '^127.0.1.1'
    line: "{{ item }}    {{ hostvars[ item ]['ansible_facts']['nodename'] }}"
  loop: "{{ ansible_play_hosts }}"

- name: Install ntp
  package:
    name: ntp
    state: present
    

- name: Start ntp 
  systemd:
    name: ntp
    state: started
