# Ansible role to setup Ambari server

---

- name: Add the HDP repository (yum)
  yum_repository:
    name: "hdp"
    description: "HDP stack version {{ hdp_version }}"
    baseurl: "{{ hdp_repo_url }}"
    state: present
    gpgcheck: no

- name: Install the ambari-server package
  package:
    name: ambari-server
    state: latest

- name: install data connector for use with mysql/mariadb
  package:
    name: mysql-connector-java
    state: latest

- name: setup ambari
  shell: ambari-server setup -s -v

- name: setup the connector
  shell: ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar
  
- name: start ambari-server
  systemd:
    name: ambari-server
    state: restarted

- name: Check that Ambari-Server is up
  uri:
    url: http://{{ ansible_host }}:8080
  register: this

- debug:
    var: this
        
    

