# Ansible role to setup Ambari server

---

- name: Install the ambari-server package
  package:
    name: ambari-server
    state: latest

- name: Install ambari standard mpacks rpm
  package:
    name: bigtop-ambari-mpack
    state: latest

- name: install data connector for use with mysql/mariadb
  package:
    name: mysql-connector-java
    state: latest

- name: setup ambari
  shell: ambari-server setup -s -v

- name: setup the connector
  shell: ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar
 
- name: install the bigtop mpack
  shell: ambari-server install-mpack --mpack=/usr/lib/bigtop-ambari-mpack/bgtp-ambari-mpack-1.0.0.0-SNAPSHOT-bgtp-ambari-mpack.tar.gz

- name: install the ODPi mpack
  shell: ambari-server install-mpack --mpack=/var/lib/ambari-server/resources/odpi-ambari-mpack-1.0.0.0-SNAPSHOT.tar.gz

- name: start ambari-server
  systemd:
    name: ambari-server
    state: restarted

- name: Check that Ambari-Server is up
  uri:
    url: http://{{ ansible_host }}:8080
  register: this

- debug:
    var: this
        
    

