# Ansible role to setup Ambari server

---

- name: Add the HDP repository (yum)
  yum_repository:
    name: "hdp"
    description: "HDP stack version {{ hdp_version }}"
    baseurl: "{{ hdp_repo_url }}"
    state: present
    gpgcheck: yes
    gpgkey: "{{ hdp_key_url }}"

- name: Install the ambari-server package
  package:
    name: ambari-server
    state: latest

- name: setup ambari
  shell: ambari-server setup -s -v

- name: start ambari-server
  systemd:
    name: ambari-server
    state: restarted

- name: Check that Ambari-Server is up
  uri:
    url: http://{{ ansible_host }}:8080
  register: this

- debug:
    var: this
        
    

