# initialise rangerdb
---
- name: create the rangerdba user with its privileges
  mysql_user:
    name: rangerdba
    host: "{{ item }}"
    password: "{{ rangerdb_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root
    login_password: "{{ root_db_password }}"
  with_items:
    - localhost
    - '%'
