# Install and start
---

- name: Install mariadb
  package:
    name: mariadb-server
    state: latest

- name: Install python mysql connector libraries
  package:
    name: 
      - python-mysql.connector
      - python-pymysql
      - python3-pymysql
    state: latest

- name: start mariadb-server
  systemd:
    name: mariadb
    enabled: yes
    state: started
