# Ansible role to install the ambari repo on all nodes

---

- name: Add the bigtop repo for Ambari repository (yum)
  yum_repository:
    name: "bigtop"
    description: "Bigtop repository for hadoop rpms"
    baseurl: "{{ repo_url }}"
    state: present
    gpgcheck: yes
    gpgkey: "{{ key_url }}"



    
