# Ansible role to install the ambari repo on all nodes

---

- name: Add bigtop key
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: Add the bigtop repo for Ambari repository (apt)
  apt_repository:
    repo: "deb http://repos.bigtop.apache.org/releases/1.5.0/ubuntu/18.04/$(ARCH) bigtop contrib"


    
